function ir_series = build_ir_series(Y_var,expectations,idx,current_cols,lag_cols)
%% BUILD_IR_SERIES Convert model paths into the fourteen reported series.

growth_rows = [idx.wage;idx.cons;idx.invst;idx.output];
y_growth = Y_var(growth_rows,current_cols)-Y_var(growth_rows,lag_cols)+ ...
    ones(numel(growth_rows),1)*Y_var(idx.gamma_x,current_cols);
y_detrended = zeros(size(y_growth));
y_detrended(:,1) = y_growth(:,1);
for period = 2:size(y_growth,2)
    y_detrended(:,period) = y_growth(:,period)+y_detrended(:,period-1);
end
ir_series = [y_detrended;Y_var(idx.bond,current_cols); ...
    Y_var(idx.hours,current_cols);Y_var(idx.rk,current_cols); ...
    Y_var(idx.wage,current_cols);expectations.Exp_rk_1Q(current_cols); ...
    expectations.Exp_w_1Q(current_cols);expectations.Exp_rk_3Q(current_cols); ...
    expectations.Exp_rk_4Q(current_cols);expectations.Exp_w_3Q(current_cols); ...
    expectations.Exp_w_4Q(current_cols)];
end
