function specification = ep_ih_learning_specification(model)
%% EP_IH_LEARNING_SPECIFICATION Declarative retained E&P IH mapping.

p = model.calibration;
weights = [p.beta_tilda-p.c_c, ...
    -p.beta_tilda*p.R_tilda*(p.beta_tilda/p.sigma-p.c_c), ...
    p.c_c*p.beta_tilda*(p.eps_w+p.eps_c*p.chi/(1-p.chi))] ...
    /p.beta_tilda;
present_values = struct( ...
    'target',{'rk','wage'}, ...
    'variable',{'rk_sum','w_sum'}, ...
    'equation',{'capital_pv','wage_pv'}, ...
    'target_scale',{1,1});
decision = struct( ...
    'equation',"ih_consumption", ...
    'remove_variables',{{'rk_sum','w_sum'}}, ...
    'forecast_targets',{{'gamma_x','rk','wage'}}, ...
    'forecast_weights',weights);
specification = struct( ...
    'learned_variables',{{'rk','wage','capital'}}, ...
    'regressors',{{ ...
        struct('name',"constant",'kind',"constant"), ...
        struct('name',"capital_lag",'kind',"lagged_variable", ...
            'variable',"capital",'lag',1)}}, ...
    'gain',struct('type',"constant",'value',0.002), ...
    'estimator',struct('method',"rls", ...
        'moment_timing',"update_before_coefficients", ...
        'rcond_tolerance',1.0856345e-10), ...
    'initialization',struct( ...
        'coefficients',struct('method',"re",'scale',1), ...
        'moments',struct('method',"stationary_re", ...
            'shock_covariance',1)), ...
    'update_timing',"decide_then_update", ...
    'projection',struct( ...
        'variable',"capital",'regressor',"capital_lag", ...
        'criterion',"absolute_limit",'limit',0.99, ...
        'action',"retain_previous_coefficient"), ...
    'expectation_mapping',struct( ...
        'method',"infinite_horizon", ...
        'options',struct( ...
            'discount',p.beta_tilda, ...
            'present_values',present_values, ...
            'decision',decision, ...
            'feedback',true)));
end
