function solution = scalar_re_solution()
%% SCALAR_RE_SOLUTION Canonical one-variable RE-law test fixture.

solution = struct( ...
    'intercept',0, ...
    'transition',0.5, ...
    'shock',1, ...
    'state_indices',1, ...
    'variable_names',{{'y'}}, ...
    'shock_names',{{'eps'}});
end
