function specification = scalar_learning_specification()
%% SCALAR_LEARNING_SPECIFICATION Minimal declarative learning input.

specification = struct( ...
    'learned_variables',{{'y'}}, ...
    'regressors',{{'constant','y_lag'}}, ...
    'gain',struct('type','constant','value',0.25), ...
    'initialization','re', ...
    'update_timing','after_observation', ...
    'projection',[]);
end
