function model = scalar_structural_model()
%% SCALAR_STRUCTURAL_MODEL Canonical one-variable structural test fixture.

model = struct( ...
    'current',1, ...
    'lag',-0.5, ...
    'lead',0.25, ...
    'shock',-1, ...
    'variable_names',{{'y'}}, ...
    'shock_names',{{'eps'}}, ...
    'equation_names',{{'scalar_equation'}}, ...
    'calibration',struct('rho',0.5), ...
    'transformation',struct('kind','deviation','scale',1));
end
