function specification = scalar_learning_specification()
%% SCALAR_LEARNING_SPECIFICATION Minimal declarative learning input.

specification = struct( ...
    'learned_variables',{{'y'}}, ...
    'regressors',{{ ...
        struct('name',"constant",'kind',"constant"), ...
        struct('name',"y_lag",'kind',"lagged_variable", ...
            'variable',"y",'lag',1)}}, ...
    'gain',struct('type','constant','value',0.25), ...
    'estimator',struct( ...
        'method',"rls", ...
        'moment_timing',"update_before_coefficients", ...
        'rcond_tolerance',1e-12), ...
    'initialization',struct( ...
        'coefficients',struct('method',"re",'scale',1), ...
        'moments',struct('method',"stationary_re", ...
            'shock_covariance',1)), ...
    'update_timing',"decide_then_update", ...
    'projection',struct( ...
        'variable',"y", ...
        'regressor',"y_lag", ...
        'criterion',"absolute_limit", ...
        'limit',0.99, ...
        'action',"retain_previous_coefficient"), ...
    'expectation_mapping',struct( ...
        'method',"one_step",'options',struct()));
end
