function sensitivity = run_ep_gain_sensitivity(varargin)
%% RUN_EP_GAIN_SENSITIVITY Compare E&P EE and IH over one common gain grid.
% Research question: how does responsiveness to new data alter amplification
% and stability in E&P one-step EE versus infinite-horizon learning?
% The documented grid is [0, .002, .005, .01, .02]. Every specification and
% gain receives exactly the same standardized innovations, training length,
% technology-growth impulse, and reporting convention. Failed draws are
% recorded and never replaced.
%
% Usage:
%   result = run_ep_gain_sensitivity();
%   result = run_ep_gain_sensitivity(config,output_directory);
%   result = run_ep_gain_sensitivity(config,output_directory,gain_grid);
% The third form supports short tests or an explicitly documented alternative.

root = setup_project();
default_gains = [0 0.002 0.005 0.01 0.02];
if nargin==0
    config = ep_experiment_config();
    output_dir = fullfile(root,'results','ep_gain_sensitivity');
    gains = default_gains;
elseif nargin==2 || nargin==3
    config = varargin{1};
    output_dir = varargin{2};
    if nargin==3, gains = varargin{3}; else, gains = default_gains; end
else
    error('EPResearch:RequiredArguments', ...
        'Supply neither, config and output directory, or those plus gains.');
end
validate_ep_experiment_config(config);
assert(isnumeric(gains) && isrow(gains) && ~isempty(gains) && ...
    all(isfinite(gains)) && all(gains>=0) && numel(unique(gains))==numel(gains), ...
    'EPResearch:InvalidGainGrid','Gains must be unique nonnegative values.');
if ~isfolder(output_dir), mkdir(output_dir); end

%% Load each verified E&P structural formulation once.
calibration = ep_calibration(config.gamma_bar);
ee_model = load_linear_dynare_model(fullfile(root,'models','ep_rbc_ee.mod'), ...
    'ParameterOverrides',calibration.parameter_overrides);
ih_model = load_linear_dynare_model(fullfile(root,'models','ep_rbc_ih.mod'), ...
    'ParameterOverrides',calibration.parameter_overrides);

%% Draw once so gain and expectations formulation are the only changes.
rng(config.random_seed,'twister');
standardized_innovations = zeros(config.draw_count, ...
    config.training_periods+config.ir_periods);
for draw = 1:config.draw_count
    standardized_innovations(draw,:) = randn(1, ...
        config.training_periods+config.ir_periods);
end

ee_results = cell(1,numel(gains));
ih_results = cell(1,numel(gains));
shock_variance = config.training_shock_standard_deviation^2;
for j = 1:numel(gains)
    gain = gains(j);
    ee_learning = build_ee_learning_model(ee_model, ...
        ep_ee_specification(gain),shock_variance);
    ee_results{j} = run_learning_specification(ee_learning, ...
        sprintf('ep_ee_gain_%g',gain),'E&P paper-faithful EE', ...
        standardized_innovations,config,config.technology_growth_impulse, ...
        @report_common_quantities,'eps_x');

    ih_learning = build_ep_ih_learning_model(ih_model, ...
        ep_ih_specification(gain),shock_variance);
    ih_results{j} = run_learning_specification(ih_learning, ...
        sprintf('ep_ih_gain_%g',gain),'E&P benchmark IH', ...
        standardized_innovations,config,config.technology_growth_impulse, ...
        @report_common_quantities,'eps_x');
end

sensitivity = struct('experiment','ep_gain_sensitivity','config',config, ...
    'calibration',calibration,'gains',gains,'default_gains',default_gains, ...
    'specification_names',{{'E&P EE','E&P IH'}}, ...
    'quantity_names',{{'output','consumption','investment','hours'}}, ...
    'standardized_innovations',standardized_innovations, ...
    'ee_results',{ee_results},'ih_results',{ih_results}, ...
    'output_files',struct());
sensitivity.summary = summarize_gain_grid({ee_results,ih_results}, ...
    {'ep_ee','ep_ih'},gains,sensitivity.quantity_names,config.plot_periods);
sensitivity = standardize_artifact(sensitivity, ...
    ['How does responsiveness to new data alter amplification and stability ' ...
    'in E&P EE and IH when all histories are held fixed?'],struct( ...
    'standardized_innovations',{{'draw','simulation_period'}}, ...
    'ee_results',{{'gain'}},'ih_results',{{'gain'}}, ...
    'summary_maximum_wedge',{{'specification','gain','quantity'}}, ...
    'summary_rates',{{'specification','gain'}}));
sensitivity.output_files = save_ep_gain_heatmap(sensitivity,output_dir);
save(sensitivity.output_files.mat,'-struct','sensitivity','-v7.3');
end
