function growth = run_ep_growth_sensitivity(varargin)
%% RUN_EP_GROWTH_SENSITIVITY Compare original and zero deterministic growth.
% Research question: does positive deterministic trend growth, rather than the
% expectations formulation, drive the E&P response differences?
% This runner executes only E&P EE and IH. Both gamma_bar calibrations use the
% same seed, standardized innovations, and structural growth impulse.

root = setup_project();
if nargin==0
    config = ep_experiment_config();
    output_dir = fullfile(root,'results','ep_growth_sensitivity');
elseif nargin==2
    config = varargin{1};
    output_dir = varargin{2};
else
    error('EPResearch:RequiredArguments', ...
        'Supply both a complete config and output directory, or neither.');
end
if ~isfolder(output_dir), mkdir(output_dir); end
baseline_config = config;
baseline_config.gamma_bar = exp(0.0053);
zero_growth_config = config;
zero_growth_config.gamma_bar = 1;
baseline = run_ep_experiment(baseline_config, ...
    fullfile(output_dir,'original_growth'),'ep_original_growth');
zero_growth = run_ep_experiment(zero_growth_config, ...
    fullfile(output_dir,'zero_growth'),'ep_zero_growth');
assert(isequal(baseline.standardized_innovations, ...
    zero_growth.standardized_innovations),'EPResearch:UnpairedGrowthTest', ...
    'Growth sensitivity did not use identical random draws.');
differences = cell(1,2);
for j = 1:2
    differences{j} = struct('id',baseline.results{j}.id, ...
        'learning_median',zero_growth.results{j}.summary.learning_median- ...
        baseline.results{j}.summary.learning_median, ...
        're',zero_growth.results{j}.summary.re-baseline.results{j}.summary.re);
end
quantity_names = {'output','consumption','investment','hours'};
growth = struct('experiment','ep_growth_sensitivity', ...
    'description',['gamma_bar=1 minus gamma_bar=exp(0.0053), holding ' ...
    'innovations and the technology-growth impulse fixed'], ...
    'config',config,'quantity_names',{quantity_names}, ...
    'baseline',baseline,'zero_growth',zero_growth, ...
    'differences',{differences},'output_files',struct());
growth.summary = summarize_growth(differences,baseline,zero_growth, ...
    config.plot_periods,quantity_names);
growth = standardize_artifact(growth, ...
    ['Are the E&P learning results driven by the original positive ' ...
    'deterministic growth rate rather than by the expectations formulation?'], ...
    struct('differences',{{'specification'}}, ...
    'difference_paths',{{'quantity','period'}}, ...
    'summary_maximum_difference',{{'specification','quantity'}}, ...
    'summary_completion_rate',{{'specification','growth_case'}}));
growth.output_files = save_ep_growth_panels(growth,output_dir);
save(growth.output_files.mat,'-struct','growth','-v7.3');
end

function summary = summarize_growth(differences,baseline,zero_growth, ...
    periods,quantity_names)
S = numel(differences);
Q = numel(quantity_names);
learning = NaN(S,Q);
re = NaN(S,Q);
completion = NaN(S,2);
attempted = NaN(S,2);
for s = 1:S
    learning(s,:) = max(abs(differences{s}.learning_median(:,periods)), ...
        [],2,'omitnan').';
    re(s,:) = max(abs(differences{s}.re(:,periods)),[],2,'omitnan').';
    original = baseline.results{s};
    zero = zero_growth.results{s};
    attempted(s,:) = [numel(original.statuses) numel(zero.statuses)];
    completion(s,:) = [original.status_counts.completed ...
        zero.status_counts.completed]./attempted(s,:);
end
summary = struct('metric_description',[ ...
    'maximum over reported periods of the absolute zero-growth-minus-' ...
    'original-growth response difference'], ...
    'response_unit',"percentage-point difference in reported response", ...
    'reported_matlab_indices',periods,'reported_horizons',periods-1, ...
    'specification_ids',{baseline.specification_ids}, ...
    'growth_cases',{{'original_growth','zero_growth'}}, ...
    'quantity_names',{quantity_names}, ...
    'maximum_absolute_learning_median_difference',learning, ...
    'maximum_absolute_re_difference',re, ...
    'attempted_draw_count',attempted,'completion_rate',completion);
end
