function result = run_nk_technology_comparison(varargin)
%% RUN_NK_TECHNOLOGY_COMPARISON Report NK real and nominal technology IRFs.
% Research question: what are the NK real, inflation, and nominal-rate
% responses to a one-percentage-point technology-growth innovation, and does
% one-step EE learning materially change the RE benchmark?
%
% The real quantities are reported in the same reconstructed level units used
% by the cross-model comparison. Inflation and the nominal rate are retained
% as proportional percentage deviations from their gross steady-state values.
% The technology and risk-premium innovations are isolated explicitly.
%
% Usage:
%   result = run_nk_technology_comparison();
%   result = run_nk_technology_comparison(config,output_directory);

root = setup_project();
if nargin==0
    config = ep_experiment_config();
    output_dir = fullfile(root,'results','nk_technology_comparison');
elseif nargin==2
    config = varargin{1};
    output_dir = varargin{2};
else
    error('EPResearch:RequiredArguments', ...
        'Supply both a complete config and an output directory, or neither.');
end
validate_ep_experiment_config(config);
if ~isfolder(output_dir), mkdir(output_dir); end

model = load_nonlinear_dynare_model( ...
    fullfile(root,'models','nk_balanced_growth.mod'), ...
    'ParameterOverrides',struct('rho_s',0,'sigma_s',0), ...
    'DeviationScales',struct('gamma_x',0.01));
shock_covariance = diag([config.training_shock_standard_deviation^2,0]);
learning_model = build_ee_learning_model(model, ...
    nk_ee_specification(config.gain),shock_covariance);

rng(config.random_seed,'twister');
standardized_innovations = zeros(config.draw_count, ...
    config.training_periods+config.ir_periods);
for draw = 1:config.draw_count
    standardized_innovations(draw,:) = randn(1, ...
        config.training_periods+config.ir_periods);
end

simulation = run_learning_specification(learning_model,'nk_technology_ee', ...
    'NK technology EE',standardized_innovations,config, ...
    config.technology_growth_impulse, ...
    @report_nk_technology_nominal_quantities,'eps_x');

result = struct('experiment','nk_technology_comparison','config',config, ...
    'shock_metadata',struct('name','eps_x','persistence',0, ...
    'innovation_scale',0.01,'impulse',config.technology_growth_impulse, ...
    'description',['one-percentage-point technology-growth innovation; ' ...
    'risk-premium innovation fixed at zero']), ...
    'quantity_names',{{'output','consumption','investment','hours', ...
    'inflation','nominal rate'}}, ...
    'standardized_innovations',standardized_innovations, ...
    'simulation',simulation,'output_files',struct());
result.summary = summarize_learning_results({simulation}, ...
    {'nk_technology_ee'},result.quantity_names,config.plot_periods);
result = standardize_artifact(result, ...
    ['What are the NK real and nominal responses to a one-percentage-point ' ...
    'technology-growth innovation, and how does one-step EE learning change ' ...
    'the RE benchmark?'], ...
    struct('standardized_innovations',{{'draw','simulation_period'}}, ...
    'summary_maximum_wedge',{{'specification','quantity'}}));
result.output_files = save_nk_nominal_panels(result,output_dir, ...
    'nk_technology_comparison', ...
    'NK response to a one-percentage-point technology-growth shock');
save(result.output_files.mat,'-struct','result','-v7.3');
end
