function artifact = run_ep_ee_consumption_audit(varargin)
%% RUN_EP_EE_CONSUMPTION_AUDIT Compare written and released EE contracts.
% With no arguments, run 100 paired draws and save under results/. Optional
% arguments are a complete E&P configuration and an output directory.

root = setup_project();
if nargin==0
    config = ep_experiment_config();
    output_dir = fullfile(root,'results','ep_ee_consumption_audit');
elseif nargin==2
    config = varargin{1};
    output_dir = varargin{2};
else
    error('EPResearch:RequiredArguments', ...
        'Supply neither argument or both a configuration and output directory.');
end
validate_ep_experiment_config(config);
assert(config.training_periods==2000 && abs(config.gain-0.002)<eps, ...
    'EPResearch:EeConsumptionAuditDesign', ...
    'The EE consumption audit fixes training at 2,000 and gain at 0.002.');
if ~isfolder(output_dir), mkdir(output_dir); end

calibration = ep_calibration(config.gamma_bar);
model = load_linear_dynare_model(fullfile(root,'models','ep_rbc_ee.mod'), ...
    'ParameterOverrides',calibration.parameter_overrides);
variants = ["paper_direct_consumption","archive_fixed_re_consumption"];
labels = {'Paper: direct consumption learning', ...
    'Released archive: consumption fixed at RE'};
rng(config.random_seed,'twister');
innovations = zeros(config.draw_count,config.training_periods+config.ir_periods);
for draw = 1:config.draw_count
    innovations(draw,:) = randn(1,size(innovations,2));
end

results = cell(1,2);
for treatment = 1:2
    learning_model = build_ee_learning_model(model, ...
        ep_ee_specification(config.gain,variants(treatment)), ...
        config.training_shock_standard_deviation^2);
    results{treatment} = run_learning_specification(learning_model, ...
        char(variants(treatment)),labels{treatment},innovations,config, ...
        config.technology_growth_impulse,@report_common_quantities,'eps_x');
end
fingerprint = innovation_fingerprint(innovations);
artifact = struct('experiment','ep_ee_consumption_specification_audit', ...
    'interpretation',['Benchmark audit of the written direct-consumption ' ...
    'forecasting contract against the economically active released-code behavior.'], ...
    'config',config,'calibration',calibration, ...
    'shock_metadata',struct('name','eps_x', ...
    'training_standard_deviation',config.training_shock_standard_deviation, ...
    'impulse',config.technology_growth_impulse, ...
    'impulse_description',[ ...
    'one-percentage-point technology-growth innovation; E&P native unit = 1']), ...
    'quantity_names',{{'output','consumption','investment','hours'}}, ...
    'variants',variants,'variant_labels',{labels}, ...
    'standardized_innovations',innovations, ...
    'pairing',struct('draw_by_draw',true,'common_source', ...
    'standardized_innovations','innovation_fingerprint', ...
    repmat(fingerprint,2,1)),'results',{results},'output_files',struct());
artifact.output_files = save_ep_ee_consumption_audit(artifact,output_dir);
save(artifact.output_files.mat,'-struct','artifact','-v7.3');
end

function value = innovation_fingerprint(innovations)
weights = reshape(1:numel(innovations),size(innovations));
value = [size(innovations),sum(innovations,'all'), ...
    sum(innovations.^2,'all'),sum(weights.*innovations,'all')];
end
