function artifact = run_ep_ih_initialization_robustness(varargin)
%% RUN_EP_IH_INITIALIZATION_ROBUSTNESS Test whether IH forgets half-RE beliefs.
% Both treatments use the same structural model, RLS moments, and shock rows.
% Only their coefficients before the first training observation differ.

root = setup_project();
if nargin==0
    config = ep_experiment_config();
    output_dir = fullfile(root,'results','ep_ih_initialization_robustness');
elseif nargin==2
    config = varargin{1};
    output_dir = varargin{2};
else
    error('EPResearch:RequiredArguments', ...
        'Supply neither argument or both a configuration and output directory.');
end
validate_ep_experiment_config(config);
assert(config.training_periods==2000 && abs(config.gain-0.002)<eps, ...
    'EPResearch:IhInitializationDesign', ...
    'IH initialization robustness fixes training at 2,000 and gain at 0.002.');
if ~isfolder(output_dir), mkdir(output_dir); end

calibration = ep_calibration(config.gamma_bar);
model = load_linear_dynare_model(fullfile(root,'models','ep_rbc_ih.mod'), ...
    'ParameterOverrides',calibration.parameter_overrides);
base = build_ep_ih_learning_model(model,ep_ih_specification(config.gain), ...
    config.training_shock_standard_deviation^2);
initializations = ["dynare_re","half_re"];

% Generate each complete history once. Passing this same matrix to each run
% makes initialization differences paired draw by draw, including failures.
rng(config.random_seed,'twister');
standardized_innovations = zeros(config.draw_count, ...
    config.training_periods+config.ir_periods);
for draw = 1:config.draw_count
    standardized_innovations(draw,:) = randn(1,size(standardized_innovations,2));
end
fingerprint = innovation_fingerprint(standardized_innovations);
results = cell(1,2);
for treatment = 1:2
    learning_model = set_initial_beliefs(base,initializations(treatment));
    results{treatment} = run_learning_specification(learning_model, ...
        sprintf('ep_ih_%s',initializations(treatment)), ...
        sprintf('E&P IH %s initialization',initializations(treatment)), ...
        standardized_innovations,config,config.technology_growth_impulse, ...
        @report_common_quantities,'eps_x');
end

artifact = struct('experiment','ep_ih_initialization_robustness', ...
    'interpretation',['Targeted test of whether half-RE coefficients are ' ...
    'forgotten after standard IH training; not a global basin-of-attraction map.'], ...
    'config',config,'calibration',calibration, ...
    'quantity_names',{{'output','consumption','investment','hours'}}, ...
    'initializations',initializations, ...
    'standardized_innovations',standardized_innovations, ...
    'pairing',struct('draw_by_draw',true, ...
    'innovation_fingerprint',repmat(fingerprint,2,1), ...
    'source_field','standardized_innovations'), ...
    'results',{results},'output_files',struct());
artifact.output_files = save_ep_ih_initialization_robustness(artifact,output_dir);
save(artifact.output_files.mat,'-struct','artifact','-v7.3');
end

function value = innovation_fingerprint(innovations)
% Compact audit value; the full innovations remain saved in the artifact.
weights = reshape(1:numel(innovations),size(innovations));
value = [size(innovations),sum(innovations,'all'), ...
    sum(innovations.^2,'all'),sum(weights.*innovations,'all')];
end
