function root = setup_project()
%% SETUP_PROJECT Add only the clean research interface to the MATLAB path.
% Returns the repository root so callers can construct stable model paths
% without depending on the caller's working directory.

root = fileparts(mfilename('fullpath'));
% Keep this checkout ahead of stale paths from another working tree. Adding
% the root also keeps SETUP_PROJECT resolvable if a test changes directory.
addpath(root,'-begin');

folders = {fullfile('src','case'), ...
    fullfile('src','study'), ...
    fullfile('src','model'), ...
    fullfile('src','learning'), ...
    fullfile('src','experiment'), ...
    fullfile('src','artifact'), ...
    fullfile('src','reporting'), ...
    fullfile('src','expectations'), ...
    'tests'};
for j = numel(folders):-1:1
    folder_path = fullfile(root,folders{j});
    if isfolder(folder_path)
        addpath(folder_path,'-begin');
    end
end
end
