function config = learning_comparison_config()
%% LEARNING_COMPARISON_CONFIG Shared settings for E&P and NK IRF panels.

config=struct('gain',0.002,'random_seed',20260721,'draw_count',100, ...
    'training_periods',2000,'ir_periods',40,'plot_periods',1:40, ...
    'band_probabilities',[0.25 0.75],'impact_output_percent',1, ...
    'nk_technology_persistence',0, ...
    'explosion_magnitude_percent',1000, ...
    'training_shock_standard_deviations',struct( ...
    'ep_ee',exp(-0.144),'ep_ih',exp(-0.034),'nk_ee',0.0025));
end
