function config = learning_comparison_config()
%% LEARNING_COMPARISON_CONFIG Shared settings for E&P and NK IRF panels.
% The active E&P EE and IH specifications share exp(-0.034), the technology
% shock scale in the original E&P impulse-response driver. The archive-only
% EE replication retains exp(-0.144) in ep_ee_archive_config because that
% value came from the original Table 5 Euler-equation simulation folders.

config=struct('gain',0.002,'random_seed',20260721,'draw_count',100, ...
    'training_periods',2000,'ir_periods',40,'plot_periods',1:40, ...
    'band_probabilities',[0.25 0.75], ...
    'technology_shock_percent',1, ...
    'ep_steady_state_growth',exp(0.0053), ...
    'nk_technology_persistence',0, ...
    'explosion_magnitude_percent',1000, ...
    'training_shock_standard_deviations',struct( ...
    'ep',exp(-0.034),'nk',0.0025));
end
