function config = make_ep_ee_comparison_config(n_draws,output_file)
%% MAKE_EP_EE_COMPARISON_CONFIG Explicit matched-comparison configuration.

assert(nargin==2,'EPEE:RequiredComparisonConfig', ...
    'n_draws and output_file are required.');
config=struct('n_draws',n_draws,'seed',20260717,'gains',[0.002 0.04], ...
    'sigmas',[1 2],'variants',{{'RE','archive','wage_proxy','paper'}}, ...
    'bootstrap_reps',2000,'bootstrap_seed',20260718, ...
    'output_file',char(output_file),'path_length',5162,'sample_start',5000, ...
    'hp_lambda',1600,'gamma_bar',exp(0.0053),'shock_scale',exp(-0.144));
end
