function config = nk_ee_ir_config()
%% NK_EE_IR_CONFIG Reproducible defaults for the primary NK EE experiment.

config=struct('gain',0.002,'random_seed',20260721,'draw_count',100, ...
    'training_periods',2000,'ir_periods',40,'plot_periods',1:40, ...
    'band_probabilities',[0.25 0.75], ...
    'training_shock_standard_deviation',0.0025, ...
    'impact_output_percent',1, ...
    'explosion_magnitude_percent',1000);
end
