classdef TestEPLegacyParity < matlab.unittest.TestCase
    %% TESTEPLEGACYPARITY Verify the 100-draw E&P acceptance standard.

    methods (Test)
        function reproducesPaperDirectEEAndBenchmarkIH(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            frozen = load(fullfile(root,'tests','fixtures', ...
                'ep_experiment_reference.mat'),'reference');
            manifest = testsupport.load_experiment_manifest(fullfile( ...
                root,'experiments','ep_comparison'));
            design = learning_irf_design(learning_irf_options());
            actual = run_comparison(cellfun(@prepare_case, ...
                manifest.case_definitions,'UniformOutput',false),design);

            reference = frozen.reference.baseline;
            for j = 1:2
                item = actual.cases{j};
                expected = reference{j};
                testCase.verifyEqual(item.case.id,string(expected.id));
                testCase.verifyEqual(item.statuses(:),string(expected.statuses(:)));
                testCase.verifyEqual(item.status_counts,expected.status_counts);
                verify_close(testCase,item.summary.learning_median, ...
                    expected.learning_median,j,"median");
                verify_close(testCase,item.summary.learning_low, ...
                    expected.learning_low,j,"lower band");
                verify_close(testCase,item.summary.learning_high, ...
                    expected.learning_high,j,"upper band");
                verify_close(testCase,item.summary.re,expected.re,j,"RE path");
            end
        end

        function matchesCompactEngineHandoffs(testCase)
            root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
            frozen = load(fullfile(root,'tests','fixtures', ...
                'ep_engine_reference.mat'),'fixture');
            options = struct('gamma_bar',frozen.fixture.gamma_bar, ...
                'gain',frozen.fixture.gain, ...
                'belief_shock_covariance', ...
                    frozen.fixture.shock_standard_deviation^2, ...
                'rcond_tolerance',1e-12, ...
                'ih_rcond_tolerance',1.0856345e-10);
            manifest = testsupport.load_experiment_manifest(fullfile( ...
                root,'experiments','ep_comparison'),options);
            definitions = manifest.case_definitions;
            ids = {'ee','ih'};
            for j = 1:2
                prepared = prepare_case(definitions{j});
                expected = frozen.fixture.(ids{j});
                verify_close(testCase,prepared.structural_model.current, ...
                    expected.current,j,"structural current matrix");
                verify_close(testCase,prepared.structural_model.lag, ...
                    expected.lag,j,"structural lag matrix");
                verify_close(testCase,prepared.structural_model.lead, ...
                    expected.lead,j,"structural lead matrix");
                verify_close(testCase,prepared.structural_model.shock, ...
                    expected.shock,j,"structural shock matrix");
                verify_close(testCase,prepared.re_solution.transition, ...
                    expected.re_transition,j,"RE transition");
                verify_close(testCase,prepared.re_solution.shock, ...
                    expected.re_shock,j,"RE shock");
                policy = struct('magnitude_limit',1000, ...
                    'reject_nonfinite',true, ...
                    'variable_indices',1:numel(prepared.learning_system.variable_names));
                specification = struct('initial_values', ...
                    zeros(numel(prepared.learning_system.variable_names),1), ...
                    'shocks',frozen.fixture.shocks,'periods', ...
                    numel(frozen.fixture.shocks),'explosion_policy',policy, ...
                    'store_belief_history',false);
                result = run_experiment(prepared.learning_system,specification);
                verify_close(testCase,result.path,expected.native_path,j,"native path");
                verify_close(testCase,result.terminal_beliefs.coefficients, ...
                    expected.final_coefficients,j,"trained coefficients");
                verify_close(testCase,result.terminal_beliefs.moment_matrix, ...
                    expected.final_moment_matrix,j,"trained moments");
            end
        end
    end
end

function verify_close(testCase,actual,expected,case_index,handoff)
error_value = max(abs(actual-expected),[],'all');
testCase.verifyLessThan(error_value,1e-10,sprintf( ...
    'Case %d mismatched at %s (maximum error %.17g).', ...
    case_index,handoff,error_value));
end
