function [plugin,state,fixed_point]=make_linear_ee_plugin(model,gain)
%% MAKE_LINEAR_EE_PLUGIN Generic full-VAR one-step learning configuration.

if nargin<2, gain=0.002; end
fixed_point=solve_plm_fixed_point(model);
assert(fixed_point.converged,'Canonical PLM-to-ALM fixed point did not converge.');
n=numel(model.variable_names);
B=[fixed_point.intercept,fixed_point.transition];
learning=struct('initial_coefficients',B,'initial_moment_matrix',eye(n+1), ...
    'gain',struct('type','constant','value',gain,'offset',500), ...
    'rcond_tolerance',1e-12,'project',[]);
state=initialize_learning_state(learning);
plugin=struct('name',[model.name ' EE learning'],'model',model,'learning',learning, ...
    'beliefs_to_plm',@(s) struct('intercept',s.coefficients(:,1), ...
    'transition',s.coefficients(:,2:end)), ...
    'plm_to_alm',@(p) plm_to_alm_linear(model,p), ...
    'regressor',@(y,t) [1;y(:,t-1)],'outcome',@(y,t) y(:,t), ...
    're_plm',struct('intercept',fixed_point.intercept,'transition',fixed_point.transition), ...
    'explosion_limit',1000);
end
