function learning_model = build_ep_ih_learning_model( ...
    model,specification,shock_variance)
%% BUILD_EP_IH_LEARNING_MODEL Compile the verified E&P IH learning contract.
% The estimated PLM has the same constant-and-lagged-capital form as EE, but
% plm_to_alm_ep_ih uses it to evaluate complete subjective future paths in the
% household decision rule. This difference in expectation formation—not a
% different RLS estimator or training sample—defines the IH comparison.

validate_contract(model,specification,shock_variance);
n = numel(model.variable_names);
outcomes = indices_of(model.variable_names,specification.learned_outcomes);
state_index = indices_of(model.variable_names,{specification.state_variable});
[re_transition,re_shock] = extract_re_law(model);
re_intercept = zeros(n,1);
covariance = stationary_covariance(re_transition,re_shock,shock_variance);
% RE population coefficients and moments are the common starting point. EE
% and IH can therefore be paired under identical innovations with differences
% attributable to their PLM-to-ALM mappings.
learning = struct('initial_coefficients', ...
    [re_intercept(outcomes),re_transition(outcomes,state_index)], ...
    'initial_moment_matrix',diag([1,covariance(state_index,state_index)]), ...
    'gain',specification.gain, ...
    'rcond_tolerance',specification.rcond_tolerance, ...
    'project',make_projection(specification,outcomes,state_index));
initial_beliefs = initialize_beliefs(learning);
learning_model = struct('name',[model.name ' benchmark IH'], ...
    'model',model,'initial_beliefs',initial_beliefs,'learning',learning, ...
    'beliefs_to_plm',@(beliefs) expand_plm(beliefs,re_intercept, ...
    re_transition,outcomes,state_index), ...
    'plm_to_alm',@(plm) plm_to_alm_ep_ih(model,plm,specification), ...
    'regressor',@(path,time) [1;path(state_index,time-1)], ...
    'outcome',@(path,time) path(outcomes,time), ...
    're_plm',struct('intercept',re_intercept,'transition',re_transition), ...
    'shock_impact',re_shock,'specification',specification);
end

function plm = expand_plm(beliefs,intercept,transition,outcomes,state_index)
plm = struct('intercept',intercept,'transition',transition);
plm.intercept(outcomes) = beliefs.coefficients(:,1);
plm.transition(outcomes,state_index) = beliefs.coefficients(:,2);
end

function callback = make_projection(specification,outcomes,state_index)
row = find(outcomes==state_index,1);
assert(~isempty(row),'EPResearch:InvalidIhSpecification', ...
    'Projected capital must be a learned outcome.');
limit = specification.projection.absolute_limit;
callback = @project;
    function [candidate,projected] = project(candidate,previous)
        projected = abs(candidate(row,2))>limit;
        if projected
            candidate(row,2) = previous(row,2);
        end
    end
end

function validate_contract(model,specification,shock_variance)
validate_structural_model(model);
required = {'formulation','learned_outcomes','regressors','state_variable', ...
    'observed_but_excluded','forecast_targets','present_value_variables', ...
    'present_value_equations','decision_equation','decision_forecast_targets', ...
    'gain','feedback','update_timing','initialization', ...
    'rcond_tolerance','projection'};
assert(isstruct(specification) && ...
    isempty(setxor(fieldnames(specification),required.')), ...
    'EPResearch:InvalidIhSpecification','IH specification is incomplete.');
assert(specification.formulation=="infinite_horizon" && ...
    isequal(specification.regressors,{'constant','capital_lag'}) && ...
    specification.initialization=="dynare_re" && ...
    specification.update_timing=="decide_then_update" && ...
    islogical(specification.feedback) && specification.feedback, ...
    'EPResearch:InvalidIhSpecification','Unsupported IH learning contract.');
assert(isnumeric(shock_variance) && isscalar(shock_variance) && ...
    shock_variance>0,'EPResearch:InvalidIhSpecification', ...
    'Shock variance must be positive.');
indices_of(model.variable_names,specification.learned_outcomes);
indices_of(model.variable_names,specification.forecast_targets);
indices_of(model.variable_names,specification.present_value_variables);
indices_of(model.shock_names,specification.observed_but_excluded);
indices_of(model.equation_names,specification.present_value_equations);
indices_of(model.equation_names,{specification.decision_equation});
indices_of(model.variable_names,specification.decision_forecast_targets);
end

function indices = indices_of(names,requested)
[found,indices] = ismember(requested,names);
assert(all(found),'EPResearch:MissingName','Missing name(s): %s.', ...
    strjoin(requested(~found),', '));
indices = indices(:);
end
