function learning_model = build_ee_learning_model(model,specification,shock_variance)
%% BUILD_EE_LEARNING_MODEL Compile a named one-step learning experiment.
% The returned learning_model is the complete contract consumed by the
% model-independent simulation loop.
% Agents estimate an affine PLM for the declared outcomes using a constant
% and lagged capital. All undeclared rows of the PLM remain fixed at their RE
% values. The observed technology innovation affects realized outcomes but is
% deliberately excluded from the forecasting regression, matching the
% paper-faithful EE information specification used by this project.

validate_structural_model(model);
required = {'variant','learned_outcomes','regressors','state_variable', ...
    'observed_but_excluded','gain','initialization','update_timing','projection'};
assert(isstruct(specification) && ...
    isempty(setxor(fieldnames(specification),required.')), ...
    'EPResearch:InvalidEeSpecification','EE specification is incomplete.');
assert(isequal(specification.regressors,{'constant','capital_lag'}) && ...
    specification.initialization=="dynare_re" && ...
    specification.update_timing=="decide_then_update", ...
    'EPResearch:InvalidEeSpecification','Unsupported EE learning contract.');
[found,outcomes] = ismember(specification.learned_outcomes,model.variable_names);
assert(all(found),'EPResearch:InvalidEeSpecification', ...
    'Model lacks a declared EE learned outcome.');
state_index = find(strcmp(model.variable_names,specification.state_variable),1);
assert(~isempty(state_index),'EPResearch:InvalidEeSpecification', ...
    'Model lacks the declared EE state variable.');
assert(all(ismember(specification.observed_but_excluded,model.shock_names)), ...
    'EPResearch:InvalidEeSpecification','Model lacks an observed EE shock.');
projected_row = find(strcmp(specification.learned_outcomes, ...
    specification.projection.outcome),1);
assert(~isempty(projected_row) && ...
    specification.projection.action=="reject_update", ...
    'EPResearch:InvalidEeSpecification','EE projection contract is invalid.');

[re_transition,re_shock] = extract_re_law(model);
re_intercept = zeros(numel(model.variable_names),1);
covariance = stationary_covariance(re_transition,re_shock,shock_variance);
% Initialize both coefficients and regressor moments at their RE population
% values. Learning is nevertheless active: subsequent stochastic observations
% move the estimates according to the selected gain.
learning = struct('initial_coefficients', ...
    [re_intercept(outcomes),re_transition(outcomes,state_index)], ...
    'initial_moment_matrix',diag([1,covariance(state_index,state_index)]), ...
    'gain',specification.gain,'rcond_tolerance',1e-12, ...
    'project',@project_state);
initial_beliefs = initialize_beliefs(learning);
learning_model = struct('name',[model.name ' paper EE'], ...
    'model',model,'initial_beliefs',initial_beliefs,'learning',learning, ...
    'beliefs_to_plm',@expand_plm, ...
    'plm_to_alm',@(plm) plm_to_alm_one_step(model,plm), ...
    'regressor',@(path,time) [1;path(state_index,time-1)], ...
    'outcome',@(path,time) path(outcomes,time), ...
    're_plm',struct('intercept',re_intercept,'transition',re_transition), ...
    'shock_impact',re_shock,'specification',specification);

    function plm = expand_plm(beliefs)
        % Insert only estimated coefficients into an otherwise RE PLM. This
        % makes the boundary between known and learned equations explicit.
        plm = struct('intercept',re_intercept,'transition',re_transition);
        plm.intercept(outcomes) = beliefs.coefficients(:,1);
        plm.transition(outcomes,state_index) = beliefs.coefficients(:,2);
    end

    function [candidate,projected] = project_state(candidate,previous)
        % Reject only an inadmissible state-slope update; retain all other
        % coefficient updates from the same observation.
        projected = abs(candidate(projected_row,2))> ...
            specification.projection.absolute_limit;
        if projected
            candidate(projected_row,2) = previous(projected_row,2);
        end
    end
end
