function components = extract_linear_components(context)
%% EXTRACT_LINEAR_COMPONENTS Convert Dynare's store into structural pieces.
% Explicit linear and nonlinear sources deliberately share Dynare's generated
% analytical dynamic_g1 path. Linear sources are evaluated at zero deviation
% and require no endogenous unit transformation.

M = context.M;
oo = context.oo;
n = M.endo_nbr;
matrices = extract_analytical_jacobian(context,zeros(n,1));

calibration = struct();
for j = 1:numel(M.param_names)
    calibration.(M.param_names{j}) = M.params(j);
end
components = struct( ...
    'current',matrices.current, ...
    'lag',matrices.lag, ...
    'lead',matrices.lead, ...
    'shock',matrices.shock, ...
    'variable_names',{M.endo_names(:).'}, ...
    'shock_names',{M.exo_names(:).'}, ...
    'equation_names',{equation_names(M,n)}, ...
    'calibration',calibration, ...
    'transformation',struct( ...
        'kind',"deviation", ...
        'level_steady_state',oo.steady_state(:), ...
        'deviation_scales',ones(n,1)));
end
