function specification = ep_ee_specification(gain,variant)
%% EP_EE_SPECIFICATION Named E&P one-step consumption-forecast contracts.
% The paper-direct variant follows equation (17). The archive-fixed variant
% captures the economically active released-code behavior: its six updated
% outcomes exclude consumption, whose forecasting row stays at Dynare RE.

if nargin<2, variant = "paper_direct_consumption"; end
switch variant
    case "paper_direct_consumption"
        learned = {'rk','consumption','capital'};
        consumption_forecast = struct('mode',"learned_outcome", ...
            'outcome','consumption');
    case "archive_fixed_re_consumption"
        learned = {'rk','wage','output','hours','caput','capital'};
        consumption_forecast = struct('mode',"fixed_re", ...
            'outcome','consumption');
    otherwise
        error('EPResearch:InvalidEeVariant', ...
            'Unknown E&P EE consumption variant: %s.',variant);
end
specification = struct('variant',variant, ...
    'learned_outcomes',{learned}, ...
    'regressors',{{'constant','capital_lag'}}, ...
    'state_variable','capital','observed_but_excluded',{{'eps_x'}}, ...
    'gain',struct('type','constant','value',gain,'offset',500), ...
    'initialization',"dynare_re",'update_timing',"decide_then_update", ...
    'projection',struct('outcome','capital','absolute_limit',0.99, ...
    'action',"reject_update"),'consumption_forecast',consumption_forecast);
end
