function specification = ep_ee_specification(gain)
%% EP_EE_SPECIFICATION Paper-faithful one-step-expectations information set.
% Equation (17) motivates forecasts for capital return, consumption, and
% next-period capital. Technology growth is observed when realized but is not
% included in the constant-and-lagged-capital forecasting regression.

specification = struct('variant',"paper", ...
    'learned_outcomes',{{'rk','consumption','capital'}}, ...
    'regressors',{{'constant','capital_lag'}}, ...
    'state_variable','capital','observed_but_excluded',{{'eps_x'}}, ...
    'gain',struct('type','constant','value',gain,'offset',500), ...
    'initialization',"dynare_re",'update_timing',"decide_then_update", ...
    'projection',struct('outcome','capital','absolute_limit',0.99, ...
    'action',"reject_update"));
end
