function specification = ep_ih_specification(gain)
%% EP_IH_SPECIFICATION Verified E&P infinite-horizon information set.
% Agents estimate returns, wages, and next-period capital from a constant and
% lagged capital. The PLM generates subjective present values rather than
% separate estimates of the Dynare present-value auxiliary variables.

specification = struct('formulation',"infinite_horizon", ...
    'learned_outcomes',{{'rk','wage','capital'}}, ...
    'regressors',{{'constant','capital_lag'}}, ...
    'state_variable','capital','observed_but_excluded',{{'eps_x'}}, ...
    'forecast_targets',{{'rk','wage'}}, ...
    'present_value_variables',{{'rk_sum','w_sum'}}, ...
    'present_value_equations',{{'capital_pv','wage_pv'}}, ...
    'decision_equation','ih_consumption', ...
    'decision_forecast_targets',{{'gamma_x','rk','wage'}}, ...
    'gain',struct('type','constant','value',gain,'offset',500), ...
    'feedback',true,'update_timing',"decide_then_update", ...
    'initialization',"dynare_re",'rcond_tolerance',1.0856345e-10, ...
    'projection',struct('outcome','capital','regressor','capital_lag', ...
    'absolute_limit',0.99,'action',"reject_update"));
end
