function options = ep_comparison_options()
%% EP_COMPARISON_OPTIONS Verified defaults for the E&P EE/IH study.

options = struct( ...
    'gain',0.002, ...
    'random_seed',20260721, ...
    'draw_count',100, ...
    'training_periods',2000, ...
    'irf_periods',40, ...
    'band_probabilities',[0.25 0.75], ...
    'shock_name',"eps_x", ...
    'training_standard_deviation',exp(-0.034), ...
    'impulse',1, ...
    'gamma_bar',exp(0.0053), ...
    'explosion_magnitude',1000);
end
