function definition = ep_ee_case(options)
%% EP_EE_CASE Define paper-direct one-step E&P learning.

if nargin<1, options = ep_case_options(); end
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
definition = struct( ...
    'id',"ep_ee", ...
    'label',"E&P paper-direct-consumption EE", ...
    'model_file',fullfile(root,'models','ep_rbc_ee.mod'), ...
    'model_options',struct('kind',"linear", ...
        'parameter_overrides',struct('gamma_bar',options.gamma_bar)), ...
    'learning_specification_factory',@(model) ee_specification(model,options), ...
    'reporting_specification',ep_reporting_specification());
end

function specification = ee_specification(~,options)
specification = common_specification(options,{'rk','consumption','capital'});
specification.expectation_mapping = struct('method',"one_step",'options',struct());
end

function specification = common_specification(options,learned)
specification = struct( ...
    'learned_variables',{learned}, ...
    'regressors',{{struct('name',"constant",'kind',"constant"), ...
        struct('name',"capital_lag",'kind',"lagged_variable", ...
            'variable',"capital",'lag',1)}}, ...
    'gain',struct('type',"constant",'value',options.gain), ...
    'estimator',struct('method',"rls", ...
        'moment_timing',"update_before_coefficients", ...
        'rcond_tolerance',options.rcond_tolerance), ...
    'initialization',struct( ...
        'coefficients',struct('method',"re",'scale',1), ...
        'moments',struct('method',"stationary_re", ...
            'shock_covariance',options.belief_shock_covariance)), ...
    'update_timing',"decide_then_update", ...
    'projection',struct('variable',"capital",'regressor',"capital_lag", ...
        'criterion',"absolute_limit",'limit',0.99, ...
        'action',"retain_previous_coefficient"), ...
    'expectation_mapping',struct());
end

function specification = ep_reporting_specification()
names = {'output','consumption','investment','hours'};
series = repmat(struct('id',"",'label',"",'unit',"percent_deviation", ...
    'transformation',struct()),1,numel(names));
for j = 1:numel(names)
    series(j).id = string(names{j}); series(j).label = string(names{j});
    if j<4
        series(j).transformation = struct('kind',"add_cumulative", ...
            'variable',string(names{j}),'cumulative_variables',{{'gamma_x'}}, ...
            'scale',1);
    else
        series(j).transformation = struct('kind',"native", ...
            'variable',string(names{j}),'scale',1);
    end
end
specification = struct('source',"irf",'series',series, ...
    'title',"E&P impulse responses",'x_label',"Quarters", ...
    'y_label',"Percent deviation");
end
