function definition = ep_ih_case(options)
%% EP_IH_CASE Define benchmark infinite-horizon E&P learning.

if nargin<1, options = ep_case_options(); end
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
ee_definition = ep_ee_case(options);
definition = struct( ...
    'id',"ep_ih", ...
    'label',"E&P benchmark IH", ...
    'model_file',fullfile(root,'models','ep_rbc_ih.mod'), ...
    'model_options',struct('kind',"linear", ...
        'parameter_overrides',struct('gamma_bar',options.gamma_bar)), ...
    'learning_specification_factory',@(model) ih_specification(model,options), ...
    'reporting_specification',ee_definition.reporting_specification);
end

function specification = ih_specification(model,options)
specification = testsupport_compatible_base(options);
p = model.calibration;
weights = [p.beta_tilda-p.c_c, ...
    -p.beta_tilda*p.R_tilda*(p.beta_tilda/p.sigma-p.c_c), ...
    p.c_c*p.beta_tilda*(p.eps_w+p.eps_c*p.chi/(1-p.chi))]/p.beta_tilda;
specification.expectation_mapping = struct('method',"infinite_horizon", ...
    'options',struct('discount',p.beta_tilda, ...
    'present_values',struct('target',{'rk','wage'}, ...
        'variable',{'rk_sum','w_sum'}, ...
        'equation',{'capital_pv','wage_pv'},'target_scale',{1,1}), ...
    'decision',struct('equation',"ih_consumption", ...
        'remove_variables',{{'rk_sum','w_sum'}}, ...
        'forecast_targets',{{'gamma_x','rk','wage'}}, ...
        'forecast_weights',weights), ...
    'feedback',true));
end

function specification = testsupport_compatible_base(options)
specification = struct( ...
    'learned_variables',{{'rk','wage','capital'}}, ...
    'regressors',{{struct('name',"constant",'kind',"constant"), ...
        struct('name',"capital_lag",'kind',"lagged_variable", ...
            'variable',"capital",'lag',1)}}, ...
    'gain',struct('type',"constant",'value',options.gain), ...
    'estimator',struct('method',"rls", ...
        'moment_timing',"update_before_coefficients", ...
        'rcond_tolerance',options.ih_rcond_tolerance), ...
    'initialization',struct( ...
        'coefficients',struct('method',"re",'scale',1), ...
        'moments',struct('method',"stationary_re", ...
            'shock_covariance',options.belief_shock_covariance)), ...
    'update_timing',"decide_then_update", ...
    'projection',struct('variable',"capital",'regressor',"capital_lag", ...
        'criterion',"absolute_limit",'limit',0.99, ...
        'action',"retain_previous_coefficient"), ...
    'expectation_mapping',struct());
end
