function options = nk_case_options()
%% NK_CASE_OPTIONS Model and learning assumptions for the NK case.
shock_scale = exp(-0.034);
options = struct('gain',0.002, ...
    'parameter_overrides',struct('rho_s',0,'sigma_s',0), ...
    'deviation_scales',struct('gamma_x',0.01), ...
    'belief_shock_covariance',diag([shock_scale^2 0]), ...
    'rcond_tolerance',1e-12);
end
