function prepared = prepare_case(definition)
%% PREPARE_CASE Resolve a readable case definition into stable core values.

validate_definition(definition);
structural_model = load_model(definition.model_file,definition.model_options);
re_solution = solve_re(structural_model);
learning_specification = definition.learning_specification_factory(structural_model);
learning_system = compile_learning( ...
    structural_model,re_solution,learning_specification);
prepared = struct('id',string(definition.id),'label',string(definition.label), ...
    'structural_model',structural_model,'re_solution',re_solution, ...
    'learning_specification',learning_specification, ...
    'learning_system',learning_system, ...
    'reporting_specification',definition.reporting_specification);
end

function validate_definition(value)
required = {'id';'label';'learning_specification_factory';'model_file'; ...
    'model_options';'reporting_specification'};
if ~isstruct(value) || ~isscalar(value) || ...
        ~isequal(sort(fieldnames(value)),required) || ...
        strlength(string(value.id))==0 || ~isscalar(string(value.id)) || ...
        strlength(string(value.label))==0 || ~isscalar(string(value.label)) || ...
        ~isa(value.learning_specification_factory,'function_handle') || ...
        ~isscalar(value.learning_specification_factory)
    error('AdaptiveLearning:InvalidCaseDefinition', ...
        'Case definition does not match the public contract.');
end
end
