%% Inactive model equation alternatives archived from model/build_model_matrices.m
%
% These alternatives were commented out in the active model builder. They are
% preserved here so the active file can focus on the equations currently used
% to construct the model matrices.

%% A0 present value of expected labor income
% Inactive alternative formulation:
% A0(w_sum, wage) = -1;
%
% A0(w_sum, wage) = -(1 - beta_tilda)*...
%     (1 + (eps_c - eps_w) / ...
%     (eps_c*(eps_H - (sigma - 1)/sigma*psi)));
%
% A0(w_sum, rk) = ...
%     (1 - beta_tilda) / ...
%     (eps_c*(eps_H - (sigma - 1)/sigma*psi))*R_tilda;
%
% A0(w_sum, gamma_x) = ...
%     -(1 - beta_tilda) / ...
%     (eps_c*(eps_H - (sigma - 1)/sigma*psi));

%% A0 present value of expected capital income
% Inactive alternative formulation:
% A0(rk_sum, w_sum) = 1;
%
% A0(rk_sum, wage) = ...
%     (eps_c*(eps_H - ((sigma - 1)/sigma)*psi))^(-1) ...
%     *(eps_w - eps_c);
%
% A0(rk_sum, rk) = ...
%     (eps_c*(eps_H - ((sigma - 1)/sigma)*psi))^(-1) ...
%     *R_tilda;
%
% A0(rk_sum, gamma_x) = ...
%     -(eps_c*(eps_H - ((sigma - 1)/sigma)*psi))^(-1) ...
%     *beta_tilda^(-1);
%
% A0(rk_sum, w_sum) = -1;
%
% A0(rk_sum, hours) = -sigma^(-1)*(1 - sigma)*psi;

%% A{4} infinite-horizon discounted expectations
% Inactive alternative formulation:
% infinite expected discounted sum of rk and w
% A{4}(w_sum, rk) = ...
%     -(1 - beta_tilda) / ...
%     (eps_c*(eps_H - (sigma - 1)/sigma*psi)) ...
%     *beta_tilda*R_tilda;
%
% A{4}(w_sum, wage) = ...
%     (1 - beta_tilda)*beta_tilda ...
%     *(1 + (eps_c - eps_w) / ...
%     (eps_c*(eps_H - (sigma - 1)/sigma*psi)));
%
% A{4}(w_sum, gamma_x) = ...
%     (1 - beta_tilda) / ...
%     (eps_c*(eps_H - (sigma - 1)/sigma*psi));
%
% A{4}(rk_sum, rk) = ...
%     -(eps_c*(eps_H - ((sigma - 1)/sigma)*psi))^(-1) ...
%     *beta_tilda*R_tilda;
%
% A{4}(rk_sum, wage) = ...
%     -(eps_c*(eps_H - ((sigma - 1)/sigma)*psi))^(-1) ...
%     *(eps_w - eps_c)*beta_tilda;

%% A{5} lagged variables
% Inactive alternative formulation:
% A{5}(w_sum, capital) = ...
%     -(1 - beta_tilda) / ...
%     (eps_c*(eps_H - (sigma - 1)/sigma*psi)) ...
%     *beta_tilda^(-1);
%
% A{5}(rk_sum, capital) = ...
%     -(eps_c*(eps_H - ((sigma - 1)/sigma)*psi))^(-1) ...
%     *beta_tilda^(-1);
