function axes = standard_simulation_axes()
%% STANDARD_SIMULATION_AXES Dimension labels shared by learning simulations.

axes = struct( ...
    're_native_path',{{'native_variable','period'}}, ...
    're_reported_path',{{'quantity','period'}}, ...
    'learning_draws',{{'draw','quantity','period'}}, ...
    'terminal_training_coefficients',{{'draw','learned_outcome','regressor'}}, ...
    'terminal_training_moments',{{'draw','regressor','regressor'}}, ...
    'training_projection_events',{{'draw'}}, ...
    'statuses',{{'draw'}});
end
