function artifact = standardize_artifact(artifact,question,axes)
%% STANDARDIZE_ARTIFACT Add common interpretation and provenance metadata.

assert(isstruct(artifact) && isscalar(artifact), ...
    'EPResearch:ArtifactSchema','Artifact must be a scalar struct.');
assert(isfield(artifact,'config') && isfield(artifact,'quantity_names'), ...
    'EPResearch:ArtifactSchema', ...
    'Artifact requires config and quantity_names before standardization.');
artifact.schema_version = "2.0.0";
artifact.question = string(question);
artifact.units = struct( ...
    'reported_responses',"percent deviation under the artifact's reporting " + ...
    "transformation; common real quantities are reconstructed level responses", ...
    'quantity_names',{artifact.quantity_names}, ...
    'quantity_units',repmat("percent deviation",1,numel(artifact.quantity_names)), ...
    'learning_minus_re_wedge',"percentage points of reported response", ...
    'completion_rate',"fraction of attempted draws", ...
    'completion_percent',"percent of attempted draws", ...
    'cumulative_absolute_response', ...
    "sum of absolute percentage-point responses over included periods");
artifact.periods = make_period_metadata(artifact.config);
artifact.axes = axes;
artifact.provenance = make_provenance(artifact.experiment);
end

function periods = make_period_metadata(config)
indices = 1:config.ir_periods;
periods = struct('frequency',"quarterly", ...
    'matlab_indices',indices,'horizons',indices-1, ...
    'impact_matlab_index',1,'impact_horizon',0, ...
    'plot_matlab_indices',config.plot_periods, ...
    'plot_horizons',config.plot_periods-1, ...
    'definition',"Column 1 is the impact response at horizon 0. " + ...
    "MATLAB column j is horizon j-1 quarters after the impulse.");
end

function provenance = make_provenance(generator)
generated = datetime('now','TimeZone','UTC', ...
    'Format',"yyyy-MM-dd'T'HH:mm:ss'Z'");
root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
[status,commit] = system(sprintf('git -C "%s" rev-parse HEAD',root));
if status~=0, commit = 'unavailable'; end
[status,worktree] = system(sprintf( ...
    'git -C "%s" status --porcelain --untracked-files=normal',root));
if status~=0, worktree = 'status unavailable'; end
provenance = struct('generated_at_utc',string(generated), ...
    'git_commit',string(strtrim(commit)), ...
    'git_worktree_dirty',logical(~isempty(strtrim(worktree))), ...
    'matlab_version',string(version), ...
    'generator',string(generator));
end
