function summary = summarize_gain_grid(result_sets,specification_ids,gains, ...
    quantity_names,periods)
%% SUMMARIZE_GAIN_GRID Standard gain-by-specification headline metrics.

S = numel(result_sets);
G = numel(gains);
Q = numel(quantity_names);
assert(S==numel(specification_ids), ...
    'EPResearch:SummaryDimensions','Result sets and specifications must align.');
wedges = NaN(S,G,Q);
completed = NaN(S,G);
explosive = NaN(S,G);
invalid = NaN(S,G);
attempted = NaN(S,G);
for s = 1:S
    assert(numel(result_sets{s})==G,'EPResearch:SummaryDimensions', ...
        'Every specification must have one result per gain.');
    for g = 1:G
        result = result_sets{s}{g};
        difference = result.summary.learning_median(:,periods)- ...
            result.summary.re(:,periods);
        wedges(s,g,:) = max(abs(difference),[],2,'omitnan');
        completed(s,g) = result.status_counts.completed;
        explosive(s,g) = result.status_counts.explosive;
        invalid(s,g) = result.status_counts.invalid;
        attempted(s,g) = numel(result.statuses);
    end
end
summary = struct('metric_description',[ ...
    'maximum over reported periods of the absolute pointwise median ' ...
    'learning-minus-own-RE response'], ...
    'response_unit',"percentage points of reported response", ...
    'reported_matlab_indices',periods,'reported_horizons',periods-1, ...
    'specification_ids',{cellstr(string(specification_ids))}, ...
    'gains',gains,'quantity_names',{quantity_names}, ...
    'maximum_absolute_median_learning_minus_re_wedge',wedges, ...
    'attempted_draw_count',attempted,'completed_draw_count',completed, ...
    'explosive_draw_count',explosive,'invalid_draw_count',invalid, ...
    'completion_rate',completed./attempted, ...
    'failure_rate',(explosive+invalid)./attempted);
end
