classdef TestInfiniteHorizonCompiler < matlab.unittest.TestCase
    %% TESTINFINITEHORIZONCOMPILER Specify declarative IH PLM-to-ALM mapping.

    methods (Test)
        function reproducesRetainedEPRELawAtREBeliefs(testCase)
            root = setup_project();
            model = load_model(fullfile(root,'models','ep_rbc_ih.mod'),struct());
            solution = solve_re(model);
            specification = testsupport.ep_ih_learning_specification(model);

            system = compile_learning(model,solution,specification);
            plm = system.belief_to_plm(system.initial_beliefs);
            alm = system.plm_to_alm(plm);

            testCase.verifyEqual(alm.intercept,solution.intercept, ...
                'AbsTol',1e-9);
            testCase.verifyEqual(alm.transition,solution.transition, ...
                'AbsTol',1e-9);
            testCase.verifyEqual(alm.shock,solution.shock,'AbsTol',1e-9);
        end

        function replacesPresentValueAndDecisionEquationsExactly(testCase)
            [model,solution,specification] = synthetic_ih_case();
            system = compile_learning(model,solution,specification);
            plm = struct('intercept',[0;0],'transition',diag([0.5 0]));

            alm = system.plm_to_alm(plm);

            discounted_slope = 0.9*0.5/(1-0.9*0.5);
            lhs = [1-0.2*discounted_slope 0; -discounted_slope 1];
            expected_transition = -(lhs\model.lag);
            expected_shock = -(lhs\model.shock);
            testCase.verifyEqual(alm.intercept,zeros(2,1),'AbsTol',1e-12);
            testCase.verifyEqual(alm.transition,expected_transition, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(alm.shock,expected_shock,'AbsTol',1e-12);
        end

        function rejectsUnstableDiscountedForecastAtRuntime(testCase)
            [model,solution,specification] = synthetic_ih_case();
            system = compile_learning(model,solution,specification);
            plm = struct('intercept',[0;0], ...
                'transition',diag([2 0]));

            testCase.verifyError(@() system.plm_to_alm(plm), ...
                'AdaptiveLearning:UnstableForecast');
        end

        function rejectsUnknownIHEquationAtCompileBoundary(testCase)
            [model,solution,specification] = synthetic_ih_case();
            specification.expectation_mapping.options. ...
                present_values.equation = 'unknown_equation';

            testCase.verifyError(@() compile_learning( ...
                model,solution,specification), ...
                'AdaptiveLearning:UnknownName');
        end
    end
end

function [model,solution,specification] = synthetic_ih_case()
beta = 0.9;
weight = 0.2;
rho = 0.3;
model = struct( ...
    'current',[1 -weight;0 1], ...
    'lag',[-rho 0;0 0], ...
    'lead',[0 0;-beta -beta], ...
    'shock',[-1;0], ...
    'variable_names',{{'y','pv'}}, ...
    'shock_names',{{'eps'}}, ...
    'equation_names',{{'decision','present_value'}}, ...
    'calibration',struct('beta',beta), ...
    'transformation',struct());
solution = struct( ...
    'intercept',zeros(2,1), ...
    'transition',diag([0.5 0]), ...
    'shock',[1;0], ...
    'state_indices',1, ...
    'variable_names',{{'y','pv'}}, ...
    'shock_names',{{'eps'}});
present_value = struct( ...
    'target',"y",'variable',"pv", ...
    'equation',"present_value",'target_scale',1);
decision = struct( ...
    'equation',"decision", ...
    'remove_variables',{{'pv'}}, ...
    'forecast_targets',{{'y'}}, ...
    'forecast_weights',weight);
specification = testsupport.scalar_learning_specification();
specification.learned_variables = {'y'};
specification.expectation_mapping = struct( ...
    'method',"infinite_horizon", ...
    'options',struct( ...
        'discount',beta, ...
        'present_values',present_value, ...
        'decision',decision, ...
        'feedback',true));
end
