classdef TestComparisonConsumers < matlab.unittest.TestCase
    %% TESTCOMPARISONCONSUMERS Keep interpretation separate from execution.

    methods (Test)
        function exposesStoredSummaryREAndStatuses(testCase)
            artifact = comparison_fixture();
            item = artifact.cases{1};
            testCase.verifyEqual(artifact_summary(item),item.summary);
            testCase.verifyEqual(artifact_re_benchmark(item), ...
                item.re_reported_path);
            testCase.verifyEqual(artifact_re_benchmark(item,"native"), ...
                item.re_native_path);
            testCase.verifyEqual(artifact_status_counts(item).completed,2);
        end

        function plotsWithoutSaving(testCase)
            artifact = comparison_fixture();
            handle = generate_comparison_irf_figure(artifact);
            cleanup = onCleanup(@() close(handle)); %#ok<NASGU>
            testCase.verifyEqual(string(handle.Visible),"off");
            testCase.verifyGreaterThanOrEqual(numel(findobj(handle,'Type','line')),4);
        end
    end
end

function artifact = comparison_fixture()
item = struct('schema_version',"2.0",'kind',"case_collection", ...
    'case',struct('id',"a",'label',"Case A"), ...
    'model',struct('name',"m",'variable_names',{{'y'}},'shock_names',{{'e'}}), ...
    'quantity_names',{{'y'}},'re_native_path',[1 0.5], ...
    're_reported_path',[1 0.5], ...
    'learning_draws',reshape([1 0.5 2 1],[2 1 2]), ...
    'summary',struct('learning_median',[1.5 0.75], ...
        'learning_low',[1 0.5],'learning_high',[2 1], ...
        're',[1 0.5],'band_probabilities',[0.25 0.75], ...
        'completed_draw_count',2), ...
    'status_counts',struct('completed',2,'explosive',0,'invalid',0), ...
    'study_design',struct('band_probabilities',[0.25 0.75]), ...
    'axes',struct('learning_draws',{{'draw','quantity','horizon'}}), ...
    'units',struct('reported_irf',"percent deviation"), ...
    'timing',struct('horizons',0:1), ...
    'provenance',struct('generator',"fixture"));
artifact = struct('schema_version',"2.0",'kind',"comparison", ...
    'case',struct('id',"comparison",'label',"Comparison"), ...
    'model',struct('name',"multiple"),'cases',{{item,item}}, ...
    'axes',struct('cases',{{'case'}}),'units',struct(), ...
    'timing',struct('horizons',0:1), ...
    'provenance',struct('generator',"fixture"));
end
