function artifact = build_training_irf_artifact(design,training,irf, ...
    status,termination)
%% BUILD_TRAINING_IRF_ARTIFACT Construct the composed schema-3 artifact.

artifact = struct('schema_version',"3.0",'kind',"training_irf", ...
    'case',training.case,'model',training.model, ...
    'learning_specification',training.learning_specification, ...
    'reporting_specification',training.reporting_specification, ...
    'study_design',design,'training',training,'irf',irf, ...
    'status',status,'termination',termination, ...
    'axes',struct('parts',{{'training','irf'}}), ...
    'units',struct('time',"periods"), ...
    'timing',struct('training_periods',design.training.periods, ...
        'irf_horizons',0:design.irf.periods-1), ...
    'provenance',struct('generator',"run_case", ...
        'case_fingerprint',training.provenance.case_fingerprint, ...
        'innovation_fingerprint',design.provenance.innovation_fingerprint));
validate_artifact(artifact);
end
