function artifact = build_case_collection_artifact(data)
%% BUILD_CASE_COLLECTION_ARTIFACT Construct one compact schema-3 collection.

required = {'case','model','learning_specification', ...
    'reporting_specification','study_design','series','re_native_path', ...
    're_reported_path','native_irfs','learning_draws', ...
    'terminal_training_coefficients','terminal_training_moments', ...
    'training_projection_events','statuses','terminations','status_counts', ...
    'summary','axes','units','timing','provenance'};
if ~isstruct(data) || ~isscalar(data) || ...
        ~isequal(sort(fieldnames(data)),sort(required(:)))
    actual = fieldnames(data);
    missing = setdiff(required,actual);
    extra = setdiff(actual,required);
    error('AdaptiveLearning:InvalidArtifact', ...
        'Case collection builder fields differ. Missing: %s. Extra: %s.', ...
        strjoin(missing,','),strjoin(extra,','));
end
artifact = struct('schema_version',"3.0",'kind',"case_collection", ...
    'case',data.case,'model',data.model, ...
    'learning_specification',data.learning_specification, ...
    'reporting_specification',data.reporting_specification, ...
    'study_design',data.study_design,'series',data.series, ...
    're_native_path',data.re_native_path, ...
    're_reported_path',data.re_reported_path, ...
    'native_irfs',data.native_irfs,'learning_draws',data.learning_draws, ...
    'terminal_training_coefficients',data.terminal_training_coefficients, ...
    'terminal_training_moments',data.terminal_training_moments, ...
    'training_projection_events',data.training_projection_events, ...
    'statuses',data.statuses,'terminations',{data.terminations}, ...
    'status_counts',data.status_counts,'summary',data.summary, ...
    'axes',data.axes,'units',data.units,'timing',data.timing, ...
    'provenance',data.provenance);
validate_artifact(artifact);
end
