function artifact = build_irf_artifact(prepared,training,design,stored_design, ...
    paired,primitive_irf,native_irf,reported,re_native,re_reported,series)
%% BUILD_IRF_ARTIFACT Construct the schema-3 reusable IRF artifact.

artifact = struct('schema_version',"3.0",'kind',"irf", ...
    'case',training.case,'model',training.model, ...
    'learning_specification',training.learning_specification, ...
    'reporting_specification',prepared.reporting_specification, ...
    'training_reference',struct('case_fingerprint', ...
        training.provenance.case_fingerprint,'innovation_fingerprint', ...
        training.provenance.innovation_fingerprint,'terminal',training.terminal), ...
    'irf_design',stored_design,'baseline',paired.baseline, ...
    'shocked',paired.shocked,'primitive_irf',primitive_irf, ...
    'native_irf',native_irf,'reported_irf',reported, ...
    're_native_path',re_native,'re_reported_path',re_reported, ...
    'series',series,'status',paired.status, ...
    'termination',paired.termination, ...
    'axes',struct('primitive_irf',{{'native_variable','primitive_time'}}, ...
        'native_irf',{{'native_variable','horizon'}}, ...
        'reported_irf',{{'series','horizon'}}, ...
        're_native_path',{{'native_variable','horizon'}}, ...
        're_reported_path',{{'series','horizon'}}), ...
    'units',struct('native_irf',"model_units",'horizon',"periods"), ...
    'timing',struct('primitive_path',"[y0,y1,...,yT]", ...
        'irf_columns',"primitive columns 2:end", ...
        'horizons',0:design.periods-1), ...
    'provenance',struct('generator',"run_irf", ...
        'case_fingerprint',case_fingerprint(prepared), ...
        'innovation_fingerprint',design.innovation_fingerprint));
validate_artifact(artifact);
end
