function artifact = build_training_artifact(prepared,design,stored_design, ...
    result,terminal)
%% BUILD_TRAINING_ARTIFACT Construct the schema-3 training artifact.

artifact = struct('schema_version',"3.0",'kind',"training", ...
    'case',struct('id',prepared.id,'label',prepared.label), ...
    'model',model_metadata(prepared.structural_model), ...
    'learning_specification',prepared.learning_specification, ...
    'reporting_specification',prepared.reporting_specification, ...
    'training_design',stored_design,'simulation_result',result, ...
    'terminal',terminal,'status',result.status, ...
    'termination',result.termination, ...
    'axes',struct('path',{{'native_variable','primitive_time'}}, ...
        'shocks',{{'shock','period'}}), ...
    'units',struct('path',"model_units",'time',"periods"), ...
    'timing',struct('primitive_path',"[y0,y1,...,yT]", ...
        'periods',0:design.periods), ...
    'provenance',struct('generator',"train_case", ...
        'case_fingerprint',case_fingerprint(prepared), ...
        'innovation_fingerprint',design.innovation_fingerprint));
validate_artifact(artifact);
end
