function metadata = model_metadata(model)
%% MODEL_METADATA Keep model metadata in artifacts without structural state.

metadata = struct('name',model.name,'backend',model.backend, ...
    'source',model.source,'variable_names',{model.variable_names}, ...
    'shock_names',{model.shock_names}, ...
    'equation_names',{model.equation_names}, ...
    'calibration',model.calibration,'transformation',model.transformation);
end
