function fingerprint = case_fingerprint(prepared)
%% CASE_FINGERPRINT Identify the declarative prepared-case boundary.
value = struct('id',prepared.id, ...
    'model',struct('name',prepared.structural_model.name, ...
        'source',prepared.structural_model.source, ...
        'variable_names',{prepared.structural_model.variable_names}, ...
        'shock_names',{prepared.structural_model.shock_names}, ...
        'calibration',prepared.structural_model.calibration, ...
        'transformation',prepared.structural_model.transformation), ...
    'learning_specification',prepared.learning_specification);
bytes = unicode2native(jsonencode(value),'UTF-8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(bytes);
hash = typecast(digest.digest(),'uint8');
fingerprint = lower(string(reshape(dec2hex(hash,2).',1,[])));
end
