function design = ep_comparison_design(options)
%% EP_COMPARISON_DESIGN Materialize the verified shared E&P study design.

if nargin<1, options = ep_comparison_options(); end
rng(options.random_seed,'twister');
innovations = zeros(options.draw_count, ...
    options.training_periods+options.irf_periods);
for draw = 1:options.draw_count
    innovations(draw,:) = randn(1,size(innovations,2));
end
design = struct( ...
    'shock_name',options.shock_name, ...
    'standardized_innovations',innovations, ...
    'training_standard_deviation',options.training_standard_deviation, ...
    'training_periods',options.training_periods, ...
    'irf_periods',options.irf_periods, ...
    'impulse',options.impulse, ...
    'initialization',struct('initial_values',"zeros"), ...
    'explosion_policy',struct('magnitude_limit',options.explosion_magnitude, ...
        'reject_nonfinite',true), ...
    'band_probabilities',options.band_probabilities, ...
    'random_seed',options.random_seed);
end
