function options = learning_irf_options()
%% LEARNING_IRF_OPTIONS Generic execution choices for training and IRFs.
options = struct('random_seed',20260721,'draw_count',100, ...
    'training_periods',2000,'irf_periods',40,'shock_name',"eps_x", ...
    'training_standard_deviation',exp(-0.034),'impulse',1, ...
    'initial_values',"zeros",'explosion_magnitude',1000, ...
    'band_probabilities',[0.25 0.75]);
end
