function design = learning_irf_design(options)
%% LEARNING_IRF_DESIGN Generate paired, reusable training and IRF inputs.
if nargin<1, options = learning_irf_options(); end
validate_options(options);
rng(options.random_seed,'twister');
innovations = zeros(options.draw_count,options.training_periods+options.irf_periods);
for draw = 1:options.draw_count
    innovations(draw,:) = randn(1,size(innovations,2));
end
training = innovations(:,1:options.training_periods);
future = innovations(:,options.training_periods+1:end);
policy = struct('magnitude_limit',options.explosion_magnitude, ...
    'reject_nonfinite',true);
design = struct( ...
    'training',struct('shock_name',options.shock_name, ...
        'standardized_innovations',training, ...
        'standard_deviation',options.training_standard_deviation, ...
        'periods',options.training_periods,'initial_values',options.initial_values, ...
        'explosion_policy',policy,'store_belief_history',false, ...
        'innovation_fingerprint',innovation_fingerprint(training)), ...
    'irf',struct('shock_name',options.shock_name, ...
        'standardized_innovations',future, ...
        'standard_deviation',options.training_standard_deviation, ...
        'periods',options.irf_periods,'impulse',options.impulse, ...
        'explosion_policy',policy,'store_belief_history',true, ...
        'innovation_fingerprint',innovation_fingerprint(future)), ...
    'summary',struct('band_probabilities',options.band_probabilities), ...
    'provenance',struct('random_seed',options.random_seed, ...
        'draw_count',options.draw_count, ...
        'innovation_fingerprint',innovation_fingerprint(innovations)));
end

function validate_options(options)
required = {'band_probabilities';'draw_count';'explosion_magnitude';'impulse'; ...
    'initial_values';'irf_periods';'random_seed';'shock_name'; ...
    'training_periods';'training_standard_deviation'};
valid = isstruct(options) && isscalar(options) && ...
    isequal(sort(fieldnames(options)),required) && integer(options.random_seed,0) && ...
    integer(options.draw_count,1) && integer(options.training_periods,0) && ...
    integer(options.irf_periods,1) && positive(options.training_standard_deviation) && ...
    positive(options.explosion_magnitude) && finite_scalar(options.impulse) && ...
    isstring(string(options.shock_name)) && isscalar(string(options.shock_name)) && ...
    strlength(string(options.shock_name))>0 && isnumeric(options.band_probabilities) && ...
    isequal(size(options.band_probabilities),[1 2]) && ...
    all(options.band_probabilities>=0 & options.band_probabilities<=1) && ...
    options.band_probabilities(1)<=options.band_probabilities(2);
if ~valid
    error('AdaptiveLearning:InvalidStudyOptions', ...
        'Learning IRF options do not match the public contract.');
end
end
function result = integer(value,minimum)
result = finite_scalar(value) && value==fix(value) && value>=minimum;
end
function result = positive(value)
result = finite_scalar(value) && value>0;
end
function result = finite_scalar(value)
result = isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end
