function artifact = run_case(prepared,design)
%% RUN_CASE Run one explicit draw through the stable core pipeline.

validate_prepared_case(prepared);
validate_design(design,true);
innovations = design.standardized_innovations;
training_innovations = innovations(1:design.training_periods);
future_innovations = innovations(design.training_periods+1:end);
training_shocks = materialize_named_shocks(prepared.learning_system.shock_names, ...
    design.shock_name,training_innovations,design.training_standard_deviation);
future_shocks = materialize_named_shocks(prepared.learning_system.shock_names, ...
    design.shock_name,future_innovations,design.training_standard_deviation);
impulse = materialize_named_shocks(prepared.learning_system.shock_names, ...
    design.shock_name,1,design.impulse);
n = numel(prepared.learning_system.variable_names);
policy = design.explosion_policy;
policy.variable_indices = 1:n;
initial_values = resolve_initial_values(design.initialization,n);
specification = struct( ...
    'training',experiment(initial_values,training_shocks,policy,false), ...
    'baseline',experiment(initial_values,future_shocks,policy,true), ...
    'shocked',experiment(initial_values,add_impact(future_shocks,impulse),policy,true));
result = run_training_irf(prepared.learning_system,specification);
native_irf = [];
if ~isempty(result.irf), native_irf = result.irf(:,2:end); end
re_native = re_irf(prepared.learning_system,design.irf_periods,impulse);
reported_irf = apply_reporting(native_irf,prepared.structural_model.variable_names, ...
    prepared.reporting_specification);
re_reported = apply_reporting(re_native,prepared.structural_model.variable_names, ...
    prepared.reporting_specification);
artifact = struct( ...
    'schema_version',"2.0",'kind',"training_irf", ...
    'case',struct('id',prepared.id,'label',prepared.label), ...
    'model',model_metadata(prepared.structural_model), ...
    'learning_specification',prepared.learning_specification, ...
    'study_design',design,'experiment_specification',specification, ...
    'simulation_result',result,'native_irf',native_irf, ...
    'reported_irf',reported_irf,'re_native_path',re_native, ...
    're_reported_path',re_reported, ...
    'quantity_names',{cellstr(string({prepared.reporting_specification.series.name}))}, ...
    'axes',artifact_axes(),'units',artifact_units(), ...
    'timing',artifact_timing(design.irf_periods), ...
    'provenance',artifact_provenance(design));
validate_artifact(artifact);
end

function specification = experiment(initial_values,shocks,policy,history)
specification = struct('initial_values',initial_values,'shocks',shocks, ...
    'periods',size(shocks,2),'explosion_policy',policy, ...
    'store_belief_history',history);
end

function shocks = add_impact(shocks,impulse)
if isempty(shocks)
    if ~isempty(impulse), error('AdaptiveLearning:InvalidStudyDesign', ...
            'IRF periods must be positive for an impulse.'); end
else
    shocks(:,1) = shocks(:,1)+impulse;
end
end

function values = resolve_initial_values(initialization,n)
if isstruct(initialization) && isscalar(initialization) && ...
        isfield(initialization,'initial_values') && ...
        string(initialization.initial_values)=="zeros"
    values = zeros(n,1);
elseif isstruct(initialization) && isscalar(initialization) && ...
        isfield(initialization,'initial_values') && ...
        isnumeric(initialization.initial_values) && ...
        numel(initialization.initial_values)==n
    values = initialization.initial_values(:);
else
    error('AdaptiveLearning:InvalidStudyDesign','Invalid initial values.');
end
end

function path = re_irf(system,periods,impulse)
alm = system.plm_to_alm(system.belief_to_plm(system.initial_beliefs));
path = zeros(numel(system.variable_names),periods);
if periods==0, return; end
path(:,1) = alm.intercept+alm.shock*impulse;
for period = 2:periods
    path(:,period) = alm.intercept+alm.transition*path(:,period-1);
end
end

function values = apply_reporting(native,names,specification)
if isempty(native), values = []; return; end
series = specification.series;
values = zeros(numel(series),size(native,2));
for j = 1:numel(series)
    [found,index] = ismember(string(series(j).variable),string(names));
    if ~found, error('AdaptiveLearning:InvalidReportingSpecification', ...
            'Unknown reporting variable.'); end
    value = native(index,:);
    for k = 1:numel(series(j).cumulative_variables)
        [found,cumulative_index] = ismember( ...
            string(series(j).cumulative_variables{k}),string(names));
        if ~found, error('AdaptiveLearning:InvalidReportingSpecification', ...
                'Unknown cumulative reporting variable.'); end
        value = value+cumsum(native(cumulative_index,:),2);
    end
    values(j,:) = series(j).scale*value;
end
end

function metadata = model_metadata(model)
metadata = struct('name',model.name,'backend',model.backend, ...
    'source',model.source,'variable_names',{model.variable_names}, ...
    'shock_names',{model.shock_names},'equation_names',{model.equation_names}, ...
    'calibration',model.calibration,'transformation',model.transformation);
end

function axes = artifact_axes()
axes = struct('native_irf',{{'native_variable','horizon'}}, ...
    'reported_irf',{{'quantity','horizon'}}, ...
    're_native_path',{{'native_variable','horizon'}}, ...
    're_reported_path',{{'quantity','horizon'}});
end

function units = artifact_units()
units = struct('native_irf',"model deviation units", ...
    'reported_irf',"percent deviation",'horizon',"quarters");
end

function timing = artifact_timing(periods)
timing = struct('primitive_path',"[y0,y1,...,yT]", ...
    'irf_columns',"primitive columns 2:end",'horizons',0:periods-1);
end

function provenance = artifact_provenance(design)
provenance = struct('generator',"run_case",'random_seed',design.random_seed, ...
    'innovation_fingerprint',innovation_fingerprint( ...
        design.standardized_innovations));
end

function validate_prepared_case(value)
required = {'id','label','structural_model','re_solution', ...
    'learning_specification','learning_system','reporting_specification'};
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value,required))
    error('AdaptiveLearning:InvalidPreparedCase','Invalid prepared case.');
end
end

function validate_design(value,one_draw)
required = {'shock_name','standardized_innovations', ...
    'training_standard_deviation','training_periods','irf_periods','impulse', ...
    'initialization','explosion_policy','band_probabilities','random_seed'};
if ~isstruct(value) || ~isscalar(value) || ~all(isfield(value,required)) || ...
        ~isnumeric(value.standardized_innovations) || ...
        (one_draw && size(value.standardized_innovations,1)~=1) || ...
        size(value.standardized_innovations,2)~= ...
            value.training_periods+value.irf_periods
    error('AdaptiveLearning:InvalidStudyDesign','Invalid study design.');
end
end
