function artifact = run_case(prepared,design)
%% RUN_CASE Convenience composition of TRAIN_CASE followed by RUN_IRF.

required = {'irf';'provenance';'summary';'training'};
if ~isstruct(design) || ~isscalar(design) || ...
        ~isequal(sort(fieldnames(design)),required)
    error('AdaptiveLearning:InvalidStudyDesign', ...
        'run_case requires a learning_irf_design value.');
end
training = train_case(prepared,design.training);
if training.status=="completed"
    irf = run_irf(prepared,training,design.irf);
    status = irf.status; termination = irf.termination;
else
    irf = [];
    status = training.status; termination = training.termination;
    termination.stage = "training";
end
artifact = struct('schema_version',"3.0",'kind',"training_irf", ...
    'case',training.case,'model',training.model, ...
    'learning_specification',training.learning_specification, ...
    'reporting_specification',training.reporting_specification, ...
    'study_design',design,'training',training,'irf',irf, ...
    'status',status,'termination',termination, ...
    'axes',struct('parts',{{'training','irf'}}), ...
    'units',struct('time',"periods"), ...
    'timing',struct('training_periods',design.training.periods, ...
        'irf_horizons',0:design.irf.periods-1), ...
    'provenance',struct('generator',"run_case", ...
        'case_fingerprint',training.provenance.case_fingerprint, ...
        'innovation_fingerprint',design.provenance.innovation_fingerprint));
validate_artifact(artifact);
end
