function artifact = run_comparison(prepared_cases,design)
%% RUN_COMPARISON Apply one paired study design to independent cases.

if ~iscell(prepared_cases) || isempty(prepared_cases) || ...
        ~isnumeric(design.standardized_innovations) || ...
        isempty(design.standardized_innovations)
    error('AdaptiveLearning:InvalidStudyDesign', ...
        'Comparison requires cases and a nonempty innovation matrix.');
end
fingerprint = innovation_fingerprint(design.standardized_innovations);
cases = cell(size(prepared_cases));
for case_index = 1:numel(prepared_cases)
    cases{case_index} = run_case_collection( ...
        prepared_cases{case_index},design,fingerprint);
end
artifact = struct('schema_version',"2.0",'kind',"comparison", ...
    'case',struct('id',"comparison",'label',"Model comparison"), ...
    'model',struct('name',"multiple",'variable_names',{{}}, ...
        'shock_names',{{}}), ...
    'study_design',design,'cases',{cases}, ...
    'axes',struct('cases',{{'case'}}), ...
    'units',struct('pairing',"identical standardized innovations"), ...
    'timing',struct('horizons',0:design.irf_periods-1), ...
    'provenance',struct('generator',"run_comparison", ...
        'innovation_fingerprint',fingerprint));
validate_artifact(artifact);
end

function artifact = run_case_collection(prepared,design,fingerprint)
draw_count = size(design.standardized_innovations,1);
runs = cell(draw_count,1);
for draw = 1:draw_count
    one = design;
    one.standardized_innovations = design.standardized_innovations(draw,:);
    runs{draw} = run_case(prepared,one);
end
first = runs{1};
native = NaN(draw_count,size(first.re_native_path,1),design.irf_periods);
reported = NaN(draw_count,size(first.re_reported_path,1),design.irf_periods);
coefficient_size = size(first.simulation_result.training.terminal_beliefs.coefficients);
moment_size = size(first.simulation_result.training.terminal_beliefs.moment_matrix);
coefficients = NaN([draw_count coefficient_size]);
moments = NaN([draw_count moment_size]);
projections = NaN(draw_count,1);
statuses = strings(draw_count,1);
terminations = cell(draw_count,1);
for draw = 1:draw_count
    run = runs{draw};
    statuses(draw) = run.simulation_result.status;
    terminations{draw} = run.simulation_result.termination;
    beliefs = run.simulation_result.training.terminal_beliefs;
    coefficients(draw,:,:) = beliefs.coefficients;
    moments(draw,:,:) = beliefs.moment_matrix;
    projections(draw) = beliefs.projection_events;
    if statuses(draw)=="completed"
        native(draw,:,:) = run.native_irf;
        reported(draw,:,:) = run.reported_irf;
    end
end
completed = statuses=="completed";
artifact = struct('schema_version',"2.0",'kind',"case_collection", ...
    'case',first.case,'model',first.model, ...
    'learning_specification',first.learning_specification, ...
    'study_design',design,'quantity_names',{first.quantity_names}, ...
    're_native_path',first.re_native_path, ...
    're_reported_path',first.re_reported_path, ...
    'native_irfs',native,'learning_draws',reported, ...
    'terminal_training_coefficients',coefficients, ...
    'terminal_training_moments',moments, ...
    'training_projection_events',projections, ...
    'statuses',statuses,'terminations',{terminations}, ...
    'status_counts',struct('completed',sum(completed), ...
        'explosive',sum(statuses=="explosive"), ...
        'invalid',sum(statuses=="invalid")), ...
    'summary',summarize_draws(reported,first.re_reported_path, ...
        design.band_probabilities), ...
    'axes',collection_axes(),'units',first.units,'timing',first.timing, ...
    'provenance',struct('generator',"run_comparison", ...
        'innovation_fingerprint',fingerprint));
validate_artifact(artifact);
end

function axes = collection_axes()
axes = struct('native_irfs',{{'draw','native_variable','horizon'}}, ...
    'learning_draws',{{'draw','quantity','horizon'}}, ...
    're_native_path',{{'native_variable','horizon'}}, ...
    're_reported_path',{{'quantity','horizon'}}, ...
    'terminal_training_coefficients', ...
        {{'draw','learned_variable','regressor'}}, ...
    'terminal_training_moments',{{'draw','regressor','regressor'}}, ...
    'training_projection_events',{{'draw'}},'statuses',{{'draw'}});
end
