function artifact = run_comparison(prepared_cases,design)
%% RUN_COMPARISON Apply one study to cases and compact each draw immediately.

if ~iscell(prepared_cases)||isempty(prepared_cases)|| ...
        ~isstruct(design)||~isfield(design,'provenance')
    error('AdaptiveLearning:InvalidStudyDesign','Invalid comparison inputs.');
end
cases=cell(size(prepared_cases));
for j=1:numel(prepared_cases)
    cases{j}=collect_case(prepared_cases{j},design);
end
artifact=struct('schema_version',"3.0",'kind',"comparison", ...
    'case',struct('id',"comparison",'label',"Model comparison"), ...
    'model',struct('name',"multiple",'variable_names',{{}},'shock_names',{{}}), ...
    'study_design',design,'cases',{cases}, ...
    'status',"completed",'termination',struct(), ...
    'axes',struct('cases',{{'case'}}), ...
    'units',struct('pairing',"identical_standardized_innovations"), ...
    'timing',struct('horizons',0:design.irf.periods-1), ...
    'provenance',struct('generator',"run_comparison", ...
        'innovation_fingerprint',design.provenance.innovation_fingerprint));
validate_artifact(artifact);
end

function artifact=collect_case(prepared,design)
draws=design.provenance.draw_count;
for draw=1:draws
    one=select_draw(design,draw);
    result=run_case(prepared,one);
    if draw==1
        n=numel(result.model.variable_names); s=numel(result.irf.series); h=design.irf.periods;
        native=NaN(draws,n,h); reported=NaN(draws,s,h);
        coefficients=NaN([draws size(result.training.terminal.beliefs.coefficients)]);
        moments=NaN([draws size(result.training.terminal.beliefs.moment_matrix)]);
        projections=NaN(draws,1); statuses=strings(draws,1); terminations=cell(draws,1);
        re_native=result.irf.re_native_path; re_reported=result.irf.re_reported_path;
        series=result.irf.series; model=result.model; case_value=result.case;
        learning=result.learning_specification; reporting=result.reporting_specification;
    end
    statuses(draw)=result.status; terminations{draw}=result.termination;
    beliefs=result.training.terminal.beliefs;
    coefficients(draw,:,:)=beliefs.coefficients; moments(draw,:,:)=beliefs.moment_matrix;
    projections(draw)=beliefs.projection_events;
    if result.status=="completed"
        native(draw,:,:)=result.irf.native_irf; reported(draw,:,:)=result.irf.reported_irf;
    end
end
counts=struct('completed',sum(statuses=="completed"), ...
    'explosive',sum(statuses=="explosive"),'invalid',sum(statuses=="invalid"));
data = struct('case',case_value,'model',model, ...
    'learning_specification',learning,'reporting_specification',reporting, ...
    'study_design',design,'series',series,'re_native_path',re_native, ...
    're_reported_path',re_reported,'native_irfs',native, ...
    'learning_draws',reported,'terminal_training_coefficients',coefficients, ...
    'terminal_training_moments',moments, ...
    'training_projection_events',projections,'statuses',statuses, ...
    'terminations',{terminations},'status_counts',counts, ...
    'summary',summarize_draws(reported,re_reported, ...
        design.summary.band_probabilities),'axes',collection_axes(), ...
    'units',struct('reported',string({series.unit})), ...
    'timing',struct('horizons',0:design.irf.periods-1), ...
    'provenance',struct('generator',"run_comparison", ...
        'case_fingerprint',case_fingerprint(prepared), ...
        'innovation_fingerprint',design.provenance.innovation_fingerprint));
artifact=build_case_collection_artifact(data);
end

function one=select_draw(design,draw)
one=design;
one.training.standardized_innovations=design.training.standardized_innovations(draw,:);
one.irf.standardized_innovations=design.irf.standardized_innovations(draw,:);
one.training.innovation_fingerprint=innovation_fingerprint( ...
    one.training.standardized_innovations);
one.irf.innovation_fingerprint=innovation_fingerprint(one.irf.standardized_innovations);
one.provenance.draw_count=1;
one.provenance.innovation_fingerprint=innovation_fingerprint([ ...
    one.training.standardized_innovations one.irf.standardized_innovations]);
end

function axes=collection_axes()
axes=struct('native_irfs',{{'draw','native_variable','horizon'}}, ...
    'learning_draws',{{'draw','series','horizon'}}, ...
    're_native_path',{{'native_variable','horizon'}}, ...
    're_reported_path',{{'series','horizon'}}, ...
    'terminal_training_coefficients',{{'draw','learned_variable','regressor'}}, ...
    'terminal_training_moments',{{'draw','regressor','regressor'}}, ...
    'training_projection_events',{{'draw'}},'statuses',{{'draw'}});
end
